#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
// #include "ui_mainwindow.h" // This will be generated by uic
#include "logentry.h"
#include "logfile.h"
#include <QFutureWatcher>
#include <QPair>
#include "logparser.h"

// Forward declarations for Qt classes used in members or method signatures
class QProgressBar;
class QLabel;
class LogViewWidget;
class QDateTimeEdit;
class QLineEdit;
class QCheckBox;
class QPushButton;
class QVBoxLayout;
class QDockWidget;
class QTreeWidget;
class QTreeWidgetItem;
class QDir;
class QMenu;
class QInputDialog; // For scan extensions

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; } // Forward declaration for the UI class
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    // Slots connected by objectName in .ui file (or via connectSlotsByName)
    void on_actionOpen_triggered();
    void on_actionFatal_toggled(bool checked);
    void on_actionError_toggled(bool checked);
    void on_actionWarn_toggled(bool checked);
    void on_actionInfo_toggled(bool checked);
    void on_actionDebug_toggled(bool checked);
    void on_actionTrace_toggled(bool checked);
    void onScanDirectoryClicked(); // Connected from ui->scanDirectoryButton
    void onConfigureScanExtensionsClicked(); // Connected from ui->configureScanExtensionsButton
    void toggleTextFilterDock(); // Connected from ui->actionToggle_Text_Filters_Panel
    void toggleDirectoryScannerDock(); // Connected from ui->actionToggle_Directory_Scanner_Panel
    void toggleTimeFilterDock(); // New slot for the time filter dock

    // Slots connected manually
    void onCurrentTabChanged(int index);
    void handleFileParsingStarted(const LogFilePtr& logFile);
    void handleFileParsingProgress(const LogFilePtr& logFile, int progressPercentage);
    void handleFileParsingFinished(const LogFilePtr& logFile, int totalEntries);
    void handleFileParsingFailed(const LogFilePtr& logFile);
    void handleTotalRowCountChanged(int totalRows);
    void updateLineInfoLabel(int currentRow, int totalRows);
    void onApplyTimeFilterClicked();
    void onResetTimeFilterClicked();
    void onApplyAllTextFiltersClicked();
    void updateFilterInputsFromModel();
    void handleModelFiltered();
    void onAddTextFilterInputClicked(); // For dynamic text filters
    void onRemoveTextFilterInputClicked(); // For dynamic text filters
    void startNextFileStatScan();
    void handleFileStatProcessed();
    void onDirectoryTreeItemDoubleClicked(QTreeWidgetItem* item, int column);
    void onDirectoryTreeContextMenuRequested(const QPoint& pos);
    void onOpenSelectedDirectoryFiles(const QStringList& filePaths);

    // Search related slots
    void onSearchNextTriggered();
    void onSearchPreviousTriggered();
    void onSearchEnterPressed();

private:
    Ui::MainWindow *ui; // Pointer to the UI class generated from mainwindow.ui

    // Widgets not fully managed by .ui (e.g. added to statusbar or dynamic content)
    QProgressBar* m_progressBar;
    QLabel* m_statusLabel;
    QLabel* m_lineInfoLabel;

    // Time filter widgets (added to ui->timeFilterToolBar)
    QDateTimeEdit* m_timeFilterFrom;
    QDateTimeEdit* m_timeFilterTo;
    QPushButton* m_applyTimeFilterButton;
    QPushButton* m_resetTimeFilterButton; // Added

    // Text Filter related widgets (dynamically created and added to ui->textFilterContentsWidget's layout)
    QWidget* m_textFilterContainerWidget; // This will be set as the widget for ui->textFilterDockWidget
    QVBoxLayout* m_textFilterLayout;      // Layout for m_textFilterContainerWidget
    QCheckBox* m_textFilterGlobalCaseSensitiveCheckBox;
    QPushButton* m_addTextFilterButton;
    QPushButton* m_applyAllTextFiltersButton;
    QList<QLineEdit*> m_textFilterInputs;
    QList<QPushButton*> m_textFilterRemoveButtons;

    // Directory Scanner related members
    QStringList m_scanFileExtensions; // To store configured extensions (e.g. {"log", "txt"})

    // Other members
    LogViewWidget* m_activeLogView;
    LogParser* m_statParser;
    QFutureWatcher<QPair<LogParser::FileStats, QString>> m_fileStatWatcher;
    QList<QString> m_filesToStatQueue;
    QMap<QString, QTreeWidgetItem*> m_filePathToTreeItemMap;

    // Setup methods
    void setupStatusBar();
    void setupTimeFilterDockContents(); // New method to set up the new dock
    void setupTextFilterDockContents(); 
    void setupDirectoryScanner();     
    void addNewTextFilterInput(const QString& initialText = QString());
    void clearTextFilterInputs();

    // Helper methods
    void connectToLogView(LogViewWidget* logView);
    void disconnectFromLogView(LogViewWidget* logView);
    void updateStatusBarDefaultText();
    void updateLogLevelFilterButtons();
    void setFilterLogLvl(LogLevel level, bool add);
    void scanDirectoryRecursive(QDir& currentDir, QTreeWidgetItem* parentItem, qint64& totalSizeAccumulator);
    void populateDirectoryScanResults(const QString& directoryPath);

};

#endif // MAINWINDOW_H
